### ISSUE TITLE
{"candidates":[],"debug_log":{},"status":"REQUEST_DENIED"}

### ISSUE THREAD

**Issue by Shizola** [adrenak/UniMap#8]
I'm getting this message when I try the FindPlaceExample scene:

{"candidates":[],"debug_log":{},"status":"REQUEST_DENIED"}

Other example scenes are throwing different errors.

**Comment by adrenak** [comment]
Looks like an issue with the Google Maps key. You need to enter it here: https://github.com/adrenak/UniMap/blob/master/Assets/Adrenak/UniMap/Scripts/Config.cs and enable the for it the APIs that you want to use.

**Comment by adrenak** [comment]
Checked this. The issue is that you need a key from the Google console.
